### ISSUE TITLE
Doc Links to modules are broken because of renaming

### ISSUE THREAD

**Issue by Asumie** [WhitestormJS/whitestorm.js#333] opened 2017-10-14 10:26 UTC
Describe your issue here.
Links to all modules are broken because of renaming

Versio
###### Version:
 - [x] v2.x.x
 - [ ] v1.x.x

###### Issue type:
 - [ ] Bug
 - [ ] Proposal/Enhancement
 - [ ] Question
 - [ ] Discussion

------

<details> 
<summary> <b>Tested on: </b> </summary>

###### Desktop
   - [ ] Chrome
   - [ ] Chrome Canary
   - [ ] Chrome dev-channel
   - [ ] Firefox
   - [ ] Opera
   - [ ] Microsoft IE
   - [ ] Microsoft Edge

###### Android
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

###### IOS
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Opera

</details> 
Links to all modules are broken because of renaming

Version

**Comment by hirako2000** [comment] 2017-10-15 05:30
Duplicate of #328

**Closed as completed by hirako2000** 2017-10-15 05:30 UTC
